version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  # pre_build:
  #   commands:
  #     # Install system dependencies
  #     - yum update -y
  #     - docker network create test
  #     - docker run --name db --network test -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mysql
      
      # - cd TrainingDjangoProject/
  #     # Install Python dependencies
  #     - pip install -r requirements.txt
  build:
    commands:
      # Run Django database migrations
      # - python manage.py makemigrations
      # - python manage.py migrate

      # # Collect static files
      # - python manage.py collectstatic --noinput
      - cd TrainingDjangoProject/
      # Build Docker image
      - docker build -t djangoecr .

      # Tag the Docker image with the ECR repository URI
      - docker tag djangoecr:latest 767397917182.dkr.ecr.ap-south-1.amazonaws.com/djangoapplication:latest
  post_build:
    commands:
      # Log in to Amazon ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 767397917182.dkr.ecr.ap-south-1.amazonaws.com
      # Push Docker image to Amazon ECR
      - docker push 767397917182.dkr.ecr.ap-south-1.amazonaws.com/djangoapplication:latest
      - echo "-----BEGIN RSA PRIVATE KEY-----        MIIG4gIBAAKCAYEAtf6oCcLld1AutycZ7QQA9w1krNw7SS35o3xoUDusJDYAHpbg        O7uyHwk2F1xKtzf9RRo3N8KWOxN+g1Bc3dnErgyOpE4NOr2w7+D1D/Ml5laBxiqb        bqjB9gCaTCvRbZ7LdmE7O8fjcxox0QKIHznqvjrY07T6kMKt7iIOXWWko1x9I8cB        D6OhbXLOnNWrdfOrovryTX24b0H9WaSyMTqJStN8S1Xa8E4p4UB9x6bVqwWfUAYm        sb68y9ZTPw3V3PhfhR+Q0xkAiCuB+sSlXyf9URjeRedT/SzravjlunUepTP4bNkV        SPON40rHh5CuuU/yeX+PYe+hQxckILEJB+uKtxpdvxV8dPleFa1vaamWIjH+kJW4        jLZOKjQqnpcLKBFzih4odGQ37IXz4/I61pmKqICTerV1/k2m+bc7UD9ZWwF/ZL0Q        T+GgqfqVhWBZXWy2e4ReE13P7kVY9Cq8dobxtmet66oDSVZOBbkVQla71CQojfb6        bUcCLatEoVs9AX/pAgMBAAECggGAKI9+x94l4fd+0dbnEknIJUdY3qWemOqkLml1        nhwOe2uFj0u04dstEXmuEnrBNCBIU/RJxiWZ8cSgd4ebit4T1W57A+dZT3QjUPLj        6xAXrEQvXAj25yy5PahYuw0w+atgURvOZb5g1LBL1fcoez0fMhJPbK9zAHxC40W3        ydzzWm0sfqLFe8TOH2Rs48tDEWCjKgmfouGYD0O3wRjRleMj4gdMNkYGK3RgJRGI        dsyZ5im0ndMhIJAP56X2m6Drvvmjfz3RqAos/F1gUg8v0VzwYra78OSLil3wm09I        dWDt1KFPKsVMUSbrre3jGl+gyEpXbBVRngfsGWNos592UdfOVH8vf6qanZKKo7ur        MhQRyYjv1rWP3s8Cp+REEAHXtYa/LHiOPIkcbbQBQUKNaPepEphcQyeArvvdQGS/        mToiVI/omrOlOlzbtuElQ+5m8PPXwZ+glvB+nR1PwLW1Ameu3GnZLtGs3VRShK7F        36lGgT1AhrQ+qftuPNN9mKNHqEU5AoHBAL4umV3H/KizqEPYa7mVSCttli7E+7P5        MMbNHudXdgpj6WPdVlPmuiN1k0ibibM2s4FAP9YzdSfi1yteovTkoHnnbZBQJkro        Jd21rxlxetd2Nx+TzTb9i0PiTXAFaWsoWnQuEKkSHgIeaaeNFIqdPNqfrQWEefSO        2JstYuR83BzLLq25Rthz5BXJyWDIsPkIMHd/f6CxTSpROh4Ka0+R6SPqiFodCOVq        A8n2A+6eR7XmpmwS7IKUpgkLd9OEmEAqWwKBwQD0+rIop/diWpF6W6EU7Ti/C88g        EH6neLvGs4KZCr5GoL1ApCBvTAzWak5bTbS/PA9J6QxA3ho0qYUYyzI02hzjDGD4        yScMbSCxSNmgeInTC9GLEC0W/pk0Xnv43h/xlr5hIjU4dJzUEUFNHon2yQ3cb5cj        jfNn/wVmUgoXz1OoGzur9+el37I1G94bWA3rjChBX92YwjeUzqHnPfpJQ1J27IVK        IWcTUBd1H3XjvNUakFhiPJO22Z3dbyM1yyQCagsCgcAJeAp8x9tFjwRetGTQraUV        PHSQyY/6qvqJu2bBf/JJnCXfqgKFVOSJpW363Hujp6KSWd+Ty6YWoU2zRBf693Mh        /qrO157AdgSEoGoiaysBlUozUUmTZlZLv/W5ERvpkO3IAQ8lS9igpGEATZ7rM972        x6J2ttzXl1EjkMPuumS/LkKZtbLYThTaHNzg670b+RNor7lsB8fexoKNQlmLcalY        93Fogy+RNJERuiUB+XF6lgxNLzgFXF9T7fU+W8i00ScCgcB7VhgKNf5rixOBGc6w        fXo7XROrngJWCIfpUwkmSe1gG58Mg1U9E3nHHYBToXylZvR/jpA3vFpPNyWmRO8D        AujWOq47svIw5GQ4PWgrzWP+WA3oSH2a/RVe807RDevhMraoqpNG2Bb5AbLxw7VM        BQ8wcxIRuW7ZZeBvElC4ig4hLYzOWKJMtaG/8UbSV3Oyqj6+IyiqtuVKyvliNabj        6bwD2bKFjumZJJKayfsNbE2R8Sg+VSc9QLSk/kYo2BxKBt8CgcA6+pXZsgengrJ6        6+3RAo2MgSrm4ZDGPjtbySFDpoxK8a8tegqYJI3mHsr0Ssiupe2OlGFcWBRpCbcZ        7+9WNCXt/+fimRmbWoSHZJeEsiSyZb9XG/0+9sGimq/skPEhSv5XEbgzUoT8sc+L        6bLqsJ8/wJUbHubCJOnbDX+K7sttcQG1fhR/VGlck/50xJODs++RUqfPDxChoe1u        0/CJBLdtrdLqCkByPW1615jjlejNYlQE9uOXkHORz95/pKPCA9g=        -----END RSA PRIVATE KEY-----        " > /root/.ssh/circleci2
      - ssh -oStrictHostKeyChecking=no -v ec2-user@ec2-13-232-252-75.ap-south-1.compute.amazonaws.com "sudo su -c './deploy.sh'"
